language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
# - pypy (something doesn't work with regex module)
install:
  - pip install pip --upgrade
  - pip install -r dev-requirements.txt
  - pip install pytest --upgrade
  - pip install coveralls
script:
  - if [ $TRAVIS_PYTHON_VERSION != 2.6 ] && [ $TRAVIS_PYTHON_VERSION != 3.5 ]; then pylint rebulk; fi
  - coverage run --source=guessit setup.py test
  - python setup.py build
after_success:
  - coveralls
