language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - pypy
install:
  - pip install pip --upgrade
  - pip install -r requirements.txt
  - pip install pytest --upgrade
  - pip install pytest-benchmark
  - pip install PyYAML coveralls
script:
  - coverage run --source=guessit setup.py test
  - python setup.py build
after_success:
  - coveralls
