language: python
python:
  - 2.6
  - 2.7
  - 3.3
install:
  - pip install https://github.com/Diaoul/babelfish/zipball/0.5.1.memory0
  - pip install coveralls
script: 
  - coverage run --source=guessit setup.py test
  - python setup.py build
after_success:
  - coveralls
